apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-config

secretGenerator:
  - name: htpass-secret
    options:
      disableNameSuffixHash: true
    files:
      - htpasswd

resources:
- htpasswd-cr.yaml
