apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
    # a list of projects joined into the service mesh
    - grumpycat
    - ci
    - cat-ci
    - cat-dev
    - cat-stage
    - cat-prod
    